### ISSUE TITLE
Cannot build Chrome Extension

### ISSUE THREAD

**Issue by jkowall** [mtalcott/google-photos-deduper#13]
Firstly, really cool project. I can't wait to see the results, it's been running for a while so far :) 

I was going to build the extension for Chrome, but I am getting this error

```
jkowall@jkhome:~/google-photos-deduper$ docker-compose -f chrome_extension/docker-compose.yml run node npm run build
ERROR: The Compose file is invalid because:
Service node has neither an image nor a build context specified. At least one must be provided.
```

**Comment by mtalcott** [comment]
@jkowall I just tried pushing a fix: https://github.com/mtalcott/google-photos-deduper/commit/6668208d178de36c3c04eaf4cb347ddd5fb13bd3. Can you pull the latest and let me know if it addresses the issue?

**Comment by jkowall** [comment]
Yep fixed it.
