### ISSUE TITLE
No upload into the Duplicate folder

### ISSUE THREAD

**Issue by wynstep** [mtalcott/google-photos-deduper#2]
Hi there,
I succeded in running the script, but unfortunately this does not move the duplicates into the Album created, so I cannot remove the files.
Any idea to fix?

Thank you!

**Comment by sid8840** [comment]
same here.
only folder got created.

**Comment by mtalcott** [comment]
This was a side project I unfortunately did not have time to finish. Apologies for the confusion, I have updated the README: https://github.com/mtalcott/google-photos-deduper-python/commit/958bbacefc2b7293138a1317832b33854c2e7d67
