### ISSUE TITLE
MaxRetryError 

### ISSUE THREAD

**Issue by mdeora** [mtalcott/google-photos-deduper#22]
After running the process for some time it starts throwing MaxRetryError.

google-photos-deduper-worker-1  | [2023-09-21 20:09:07,653: ERROR/ForkPoolWorker-25] Task app.tasks.store_images[04069794-2d4d-4e60-9c1c-8b7c3ec287cc] raised unexpected: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='lh3.googleusercontent.com', port=443): Max retries exceeded with url: /lr/AAJ1LKfwsu7RuSBKHHMfm0N9oHB-ukYJf_aJQ8AXs-51YZ4g8IPOPVlEtie0F_guBhuRsTzLO0ZzGEpaCBbpoBrV-UbhtAHWjCyUmiGgFU6q2QwKQf9iQCK7Fp07lDJKtMX1I4q1nfmc4YR6JIo1KQI5LEpypvdmxswZvFotFyDXNKhgN674UK2QipnwSpHnflkt16lbPRwi589MrnqtTuRsefVod9KQRwq74mL3jefNHPbQFcWt8JYbnGFTEpThs4w0p-AMiw3hiOAr3anCm7Yy1yBettFaQC3bCkpq39X-u-LdSr9RPEIKrvOpXXyDhuZWB3Slz0Mh0d18Y_mNOj65r9zt9qDII3hOWqT0T3wp_lP7gyNVbsyc5faWy4dH8JLesgComiSNy80_E4dE2LlLmaqC8J2pvnNHfknJoSNYPRMMCANTOmOV27rDNvpHp5IQmsnScIK_vhCLmFVxbzzFJAe4HyY99XF1Z3fhbDg66Zv9GqhUpx1ESAI8oUZ9WbVKpUWacjuIAahQ53VSn0680JQqZ3wsE4nvZyCWNpomDvB4eNrQHuJ4QFGojLpZwkae8zDSJgUa6V2QwBCdFkxZapksVLPurjf1RIvgx7KVlDL_T0FmLtBk-YlGPMbarQuWVzoIIzr1STnVVb-3oaVDI7Ye1Ym4bw80aaCWdbOd7jmgDviYT4I9acqe3pgy1JJktfWRRuFAnnE2txWB3pgfO1W00bVUZ_aQy0fek92C4SUW-tXoxfwGsFCjce5QyLlBQAEIpwkejdH4OJgQaDq68_XNtLL88BOfqgNeoroJNeF2T_NMVr-cMF73wD_xgdGI6Hhm0_k9juostJHaSqM-l88cs5O49b4EboDaXqFSjwRU7f7UhOYq4eYarwNxYobkgj7wmI-UA_ctlkiOx5BeW5VTyEmaycTrQCmcFCn9ZQo9p9nutUA7h9lvBbVY39Eg-4mPEOuVTJKCkf-gXfpL3gbAsHcgsPhhGyRjuKPC3D7prswAh2GmM7kSIOXLrA=w250-h250 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff6dce9160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"))
google-photos-deduper-worker-1  | Traceback (most recent call last):
google-photos-deduper-worker-1  |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
google-photos-deduper-worker-1  |     conn = connection.create_connection(
google-photos-deduper-worker-1  |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
google-photos-deduper-worker-1  |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
google-photos-deduper-worker-1  |   File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
google-photos-deduper-worker-1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
google-photos-deduper-worker-1  | socket.gaierror: [Errno -3] Temporary failure in name resolution
google-photos-deduper-worker-1  | 
google-photos-deduper-worker-1  | During handling of the above exception, another exception occurred:
google-photos-deduper-worker-1  | 
google-photos-deduper-worker-1  | Traceback (most recent call last):
google-photos-deduper-worker-1  |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
google-photos-deduper-worker-1  |     httplib_response = self._make_request(
google-photos-deduper-worker-1  |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
google-photos-deduper-worker-1  |     self._validate_conn(conn)
google-photos-deduper-worker-1  |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
google-photos-deduper-worker-1  |     conn.connect()
google-photos-deduper-worker-1  |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 363, in connect
google-photos-deduper-worker-1  |     self.sock = conn = self._new_conn()
google-photos-deduper-worker-1  |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
google-photos-deduper-worker-1  |     raise NewConnectionError(
google-photos-deduper-worker-1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0xffff6dce9160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

**Comment by mtalcott** [comment]
The "Temporary failure in name resolution" makes me think this was a temporary DNS error, I'm guessing due to an unstable internet connection. If you try again, does it succeed?
