### ISSUE TITLE
Server 404

### ISSUE THREAD

**Issue by gabrielle-me** [mtalcott/google-photos-deduper#25]
Hi! No matter what I try and in which port, I'm always getting 404 when trying to connect to the server through http://localhost

Does anyone have this issue and can give me ideas? I have no idea what's going wrong since it seems to be running correctly, but when I try to access localhost in my browser, that's what my terminal shows:

google-photos-deduper-main-server-1  | 192.168.65.1 - - [04/Oct/2023 20:26:13] "GET / HTTP/1.1" 404 -
google-photos-deduper-main-server-1  | 192.168.65.1 - - [04/Oct/2023 20:26:13] "GET / HTTP/1.1" 404 -

I already tried every solution from ChatGPT and it's still not working. The flask has to be the problem, since the client opens a page at localhost:3000

Thanks in advance for any help!

**Comment by mtalcott** [comment]
@GabiHeinrichs Hmm, the `nginx` container (e.g. `google-photos-deduper-nginx-1`) should be getting the traffic to localhost, not the `server` (`google-photos-deduper-main-server-1` in your logs).

Are you running [Docker Desktop](https://github.com/mtalcott/google-photos-deduper/blob/main/README.md#setup), or are you using a different Docker installation?
