### ISSUE TITLE
Help with "Set up local environment variables."

### ISSUE THREAD

**Issue by anthonyjclarke** [mtalcott/google-photos-deduper#37]
Apologies in advance, a complete "terminal" noobie here.... but nearly there... diligently followed all steps and now at this one.

1. cp example.env .env - **DONE and verified by using "vim .env" and I am editing a file**

3. Generate [FLASK_SECRET_KEY](https://flask.palletsprojects.com/en/2.3.x/config/#SECRET_KEY) with python -c 'import secrets; print(secrets.token_hex())' and add it to .env. - **DONE - I had to run "python3 xxx" but generated a long Key that I copied and in the first line of .env I replaced "FLASK_SECRET_KEY=XYZ" with my secret Key overwriting "XYZ" what was there from the "I assume" example.env file**

4. Add GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET from the client_id and client_secret values from the client secret file created above.

**This is where I am stuck, where do I get GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET from the client secret file... is this the JSON File created in the step before "Go to APIs & Services > Credentials > Create Credentials > OAuth client ID" ? I would appreciate unpacking this step with some more detail.**

Really appreciate any help.  Thanks

**Comment by mtalcott** [comment]
The third step actually includes a whole subsection with more explicit steps. If you click on it, it should expand:

![Screenshot 2024-01-18 212725](https://github.com/mtalcott/google-photos-deduper/assets/354599/9cd9cd39-0b23-41a9-8a64-94ce51066e83)


Of course, I acknowledge this is still a very involved setup and of course is not ideal! Eventually I would like to provide a [hosted web application](https://github.com/mtalcott/google-photos-deduper/wiki#hosted-app) and avoid all this, but it requires a larger time investment than I'm currently able to make.

**Comment by mtalcott** [comment]
Hi @anthonyjclarke,

You should be able to open the client secret file with a text editor and see something like [this JSON structure](https://developers.google.com/api-client-library/dotnet/guide/aaa_client_secrets):

```json
{
  "web": {
    "client_id": "asdfjasdljfasdkjf",
    "client_secret": "1912308409123890",
    "redirect_uris": ["https://www.example.com/oauth2callback"],
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://accounts.google.com/o/oauth2/token"
  }
}
```

In this example, your `GOOGLE_CLIENT_ID` is `asdfjasdljfasdkjf` and your `GOOGLE_CLIENT_SECRET` is `1912308409123890`.

Alternatively, these are also available for me in the [Google Cloud Console under APIs & Services > Credentials](https://console.cloud.google.com/apis/credentials) once you click on an entry in the `OAuth 2.0 Client IDs` list.

**Comment by mtalcott** [comment]
I also want to acknowledge this setup is very involved, and prevents most people from using the tool! This setup is what I could scrap together with the limited time I am able to set aside for this project.

In the future I'd like to provide a [hosted web app](https://github.com/mtalcott/google-photos-deduper/wiki#hosted-app) that avoids all this. Unfortunately, it requires a bigger time investment than I'm currently able to make.

**Comment by anthonyjclarke** [comment]
Thanks. I've taken my time and done very slowly and cautiously. Nearly there.
