### ISSUE TITLE
Error Building Image

### ISSUE THREAD

**Issue by anthonyjclarke** [mtalcott/google-photos-deduper#38]
Safely at the next install step, wonder if there is any advice you can give on where to go next ;-)

anthonyjclarke@Anthonys-MBP google-photos-deduper % docker-compose up
[+] Running 36/36
 ✔ flower 9 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                     37.3s 
   ✔ 9fda8d8052c6 Pull complete                                                                           27.1s 
   ✔ e7ae3e644d56 Pull complete                                                                           28.3s 
   ✔ 4da8ee49dcce Pull complete                                                                           30.3s 
   ✔ 7c6a85daf644 Pull complete                                                                           30.4s 
   ✔ 35f63c7ece91 Pull complete                                                                           30.7s 
   ✔ c4c0cbd43a96 Pull complete                                                                           31.4s 
   ✔ adcb2fdba780 Pull complete                                                                           32.7s 
   ✔ ae1f36545ccf Pull complete                                                                           31.7s 
   ✔ aa6324cb4929 Pull complete                                                                           32.4s 
 ✔ redis 8 layers [⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                       13.0s 
   ✔ a5573528b1f0 Pull complete                                                                            3.6s 
   ✔ 5510d86d1248 Pull complete                                                                            0.8s 
   ✔ da38f099d0c0 Pull complete                                                                            0.8s 
   ✔ 1c7eb85776c1 Pull complete                                                                            3.8s 
   ✔ b01ad51b2004 Pull complete                                                                            8.6s 
   ✔ ced83491d1f3 Pull complete                                                                            4.4s 
   ✔ 4f4fb700ef54 Pull complete                                                                            4.6s 
   ✔ 4ee968e6f056 Pull complete                                                                            5.1s 
 ✔ mongo 9 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                      31.8s 
   ✔ d519a3a2a796 Pull complete                                                                            9.1s 
   ✔ 352ba6b7451f Pull complete                                                                            6.9s 
   ✔ a6ded4191389 Pull complete                                                                           10.2s 
   ✔ c0ab25682bfe Pull complete                                                                           10.3s 
   ✔ fb81d91cc097 Pull complete                                                                           10.8s 
   ✔ ac8819c2b7ec Pull complete                                                                           10.9s 
   ✔ 73d757d8e05c Pull complete                                                                           11.4s 
   ✔ bc3edf585167 Pull complete                                                                           26.4s 
   ✔ 304d69c595fa Pull complete                                                                           11.9s 
 ✔ nginx 6 layers [⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                         33.8s 
   ✔ 8897d65c8417 Pull complete                                                                           29.3s 
   ✔ fbc138d1d206 Pull complete                                                                           13.1s 
   ✔ 06f386eb9182 Pull complete                                                                           16.4s 
   ✔ aeb2f3db77c3 Pull complete                                                                           19.1s 
   ✔ 64fb762834ec Pull complete                                                                           21.3s 
   ✔ e5a7e61f6ff4 Pull complete                                                                           26.0s 
[+] Building 214.2s (30/35)                                                                                                                                        docker:desktop-linux
 => [worker internal] load .dockerignore                                                                                                                                          10.1s
 => => transferring context: 328B                                                                                                                                                 10.0s
 => [worker internal] load build definition from Dockerfile                                                                                                                       10.1s
 => => transferring dockerfile: 1.07kB                                                                                                                                            10.0s
 => [server internal] load build definition from Dockerfile                                                                                                                       10.1s
 => => transferring dockerfile: 1.07kB                                                                                                                                            10.0s
 => [server internal] load .dockerignore                                                                                                                                          10.1s
 => => transferring context: 328B                                                                                                                                                 10.0s
 => [client internal] load .dockerignore                                                                                                                                          10.1s
 => => transferring context: 136B                                                                                                                                                 10.0s
 => [client internal] load build definition from Dockerfile                                                                                                                       10.0s
 => => transferring dockerfile: 271B                                                                                                                                              10.0s
 => [worker internal] load metadata for docker.io/library/python:3.9                                                                                                              24.8s
 => [client internal] load metadata for docker.io/library/node:20-alpine                                                                                                          23.6s
 => [worker auth] library/python:pull token for registry-1.docker.io                                                                                                               0.0s
 => [client auth] library/node:pull token for registry-1.docker.io                                                                                                                 0.0s
 => [client 1/6] FROM docker.io/library/node:20-alpine@sha256:8e6a472eb9742f4f486ca9ef13321b7fc2e54f2f60814f339eeda2aff3037573                                                    19.8s
 => => resolve docker.io/library/node:20-alpine@sha256:8e6a472eb9742f4f486ca9ef13321b7fc2e54f2f60814f339eeda2aff3037573                                                            0.0s
 => => sha256:8e6a472eb9742f4f486ca9ef13321b7fc2e54f2f60814f339eeda2aff3037573 1.43kB / 1.43kB                                                                                     0.0s
 => => sha256:6dbf56a08bcade5ee1e2196cce346182ab52bad9dcf308f4bc7b36eefb318662 1.16kB / 1.16kB                                                                                     0.0s
 => => sha256:9d9d9a7b83de49f3f37b8410fb205135c4fb279835e43d6ecaf75eb755dc2b9e 7.15kB / 7.15kB                                                                                     0.0s
 => => sha256:c303524923177661067f7eb378c3dd5277088c2676ebd1cd78e68397bb80fdbf 3.35MB / 3.35MB                                                                                     0.7s
 => => sha256:2ec53874fe288a72a8b7207e1695ec626ea0bc80a7c3fa3e872c694d1605add7 42.01MB / 42.01MB                                                                                  18.8s
 => => sha256:3946ff1ba9858829b3ccbb2f4b3e06515829d3847659ea96287591a76801fe29 2.34MB / 2.34MB                                                                                     1.1s
 => => extracting sha256:c303524923177661067f7eb378c3dd5277088c2676ebd1cd78e68397bb80fdbf                                                                                          0.1s
 => => sha256:aa2987d39b19e8c4f23a1841693e2ea0b850c3817af22d9a0623b2c9c351ef8b 446B / 446B                                                                                         0.9s
 => => extracting sha256:2ec53874fe288a72a8b7207e1695ec626ea0bc80a7c3fa3e872c694d1605add7                                                                                          0.8s
 => => extracting sha256:3946ff1ba9858829b3ccbb2f4b3e06515829d3847659ea96287591a76801fe29                                                                                          0.0s
 => => extracting sha256:aa2987d39b19e8c4f23a1841693e2ea0b850c3817af22d9a0623b2c9c351ef8b                                                                                          0.0s
 => [client internal] load build context                                                                                                                                          10.0s
 => => transferring context: 192.87kB                                                                                                                                             10.0s
 => [server base 1/5] FROM docker.io/library/python:3.9@sha256:3d9dbe78e1f45ed2eb525b462cdb02247cc0956713325aeeffa37cb5f2c8c42e                                                   50.1s
 => => resolve docker.io/library/python:3.9@sha256:3d9dbe78e1f45ed2eb525b462cdb02247cc0956713325aeeffa37cb5f2c8c42e                                                                0.0s
 => => sha256:5665c1f9a9e17acd68ae05b2839df402eac34afdd095f8c115f09886d757840c 49.59MB / 49.59MB                                                                                  32.9s
 => => sha256:3d9dbe78e1f45ed2eb525b462cdb02247cc0956713325aeeffa37cb5f2c8c42e 1.86kB / 1.86kB                                                                                     0.0s
 => => sha256:a22b9266997b4821003361a296574dd60cd31603abd7483f6d8d5e6308b273bc 7.34kB / 7.34kB                                                                                     0.0s
 => => sha256:f419b1a62fc83850ab3cb43274970bb20a18ae6e674535478a48f5bee11559b6 23.58MB / 23.58MB                                                                                   3.1s
 => => sha256:219b621d810b25485a046dbb4aa5ba50cd1190a775438449a245b2558a06c39e 2.01kB / 2.01kB                                                                                     0.0s
 => => sha256:76b4f1810f998c1f1580e2404b2e7fed8e264902d898bbe531443ea9789b7641 63.99MB / 63.99MB                                                                                  11.7s
 => => sha256:1c176cbf649709b5d8a03720a6c53e18e33ad50feef33abe83c5ae95c5aabdb2 202.50MB / 202.50MB                                                                                45.4s
 => => sha256:ba0d9396537e9f0e9dfcfdbc88e19bf081ba7c18180e6db53fa370789e309f4d 6.47MB / 6.47MB                                                                                    25.6s
 => => sha256:cf458769c92c44dc19dd1117e06e84d0c974725309b0cffd50cad029495ec3db 15.54MB / 15.54MB                                                                                  37.5s
 => => extracting sha256:5665c1f9a9e17acd68ae05b2839df402eac34afdd095f8c115f09886d757840c                                                                                          1.4s
 => => sha256:a76a1914532c78be4cfa274a122f28dec35a574ec6a723116e1a757df7b89a9e 245B / 245B                                                                                        33.7s
 => => sha256:03729fef6de7c3f230cffcba7e29e29cdc6f1f51b14acd24d0d546ca940333ca 2.85MB / 2.85MB                                                                                    35.6s
 => => extracting sha256:f419b1a62fc83850ab3cb43274970bb20a18ae6e674535478a48f5bee11559b6                                                                                          0.4s
 => => extracting sha256:76b4f1810f998c1f1580e2404b2e7fed8e264902d898bbe531443ea9789b7641                                                                                          1.6s
 => => extracting sha256:1c176cbf649709b5d8a03720a6c53e18e33ad50feef33abe83c5ae95c5aabdb2                                                                                          3.9s
 => => extracting sha256:ba0d9396537e9f0e9dfcfdbc88e19bf081ba7c18180e6db53fa370789e309f4d                                                                                          0.2s
 => => extracting sha256:cf458769c92c44dc19dd1117e06e84d0c974725309b0cffd50cad029495ec3db                                                                                          0.3s
 => => extracting sha256:a76a1914532c78be4cfa274a122f28dec35a574ec6a723116e1a757df7b89a9e                                                                                          0.0s
 => => extracting sha256:03729fef6de7c3f230cffcba7e29e29cdc6f1f51b14acd24d0d546ca940333ca                                                                                          0.1s
 => [worker internal] load build context                                                                                                                                          10.1s
 => => transferring context: 266.71kB                                                                                                                                             10.0s
 => [server internal] load build context                                                                                                                                          10.0s
 => => transferring context: 266.71kB                                                                                                                                             10.0s
 => [client 2/6] WORKDIR /app                                                                                                                                                      0.2s
 => [client 3/6] COPY package.json ./                                                                                                                                              0.0s
 => [client 4/6] COPY package-lock.json ./                                                                                                                                         0.0s
 => [client 5/6] RUN npm ci && npm cache clean --force                                                                                                                            18.9s
 => [client 6/6] COPY ./ ./                                                                                                                                                        0.0s
 => [client] exporting to image                                                                                                                                                    1.7s
 => => exporting layers                                                                                                                                                            1.7s
 => => writing image sha256:e5fcf62adc8ed54a2bdbebe28e271d7724f044cfdceb863aafff60b7562c59f1                                                                                       0.0s
 => => naming to docker.io/library/google-photos-deduper-client                                                                                                                    0.0s
 => [server base 2/5] RUN apt-get update && apt-get install -y     python3-opencv     && rm -rf /var/lib/apt/lists/*                                                              41.4s
 => [worker base 3/5] WORKDIR /usr/src/app                                                                                                                                         0.0s
 => [server base 4/5] COPY requirements.txt ./                                                                                                                                     0.0s
 => [server base 5/5] RUN pip install --no-cache-dir -r requirements.txt                                                                                                          61.4s
 => [server dev 1/3] COPY requirements-dev.txt ./                                                                                                                                  0.0s
 => [server dev 2/3] RUN pip install --no-cache-dir -r requirements-dev.txt                                                                                                        4.2s
 => [server dev 3/3] COPY . .                                                                                                                                                      0.0s
 => [server] exporting to image                                                                                                                                                    2.0s
 => => exporting layers                                                                                                                                                            2.0s
 => => writing image sha256:0398252e2ec3119865f40d877561ae5148a7d4e78b129bf736aa69b8f8d370e2                                                                                       0.0s
 => => naming to docker.io/library/google-photos-deduper-server                                                                                                                    0.0s
 => [worker] exporting to image                                                                                                                                                    2.0s
 => => exporting layers                                                                                                                                                            2.0s
 => => writing image sha256:117005aa23030cf4aa886bc7d37489070a24de5c09f8bae8aa2a08b32cbdd893                                                                                       0.0s
 => => naming to docker.io/library/google-photos-deduper-worker                                                                                                                    0.0s
[+] Running 10/10
 ✔ Network google-photos-deduper_default               Created                                                                                                                     0.0s 
 ✔ Volume "google-photos-deduper_image-volume"         Created                                                                                                                     0.0s 
 ✔ Volume "google-photos-deduper_client-node-modules"  Created                                                                                                                     0.0s 
 ✔ Container google-photos-deduper-client-1            Created                                                                                                                     2.8s 
 ✔ Container google-photos-deduper-mongo-1             Created                                                                                                                     0.1s 
 ✔ Container google-photos-deduper-redis-1             Created                                                                                                                     0.1s 
 ✔ Container google-photos-deduper-flower-1            Created                                                                                                                     0.1s 
 ✔ Container google-photos-deduper-server-1            Created                                                                                                                     0.1s 
 ✔ Container google-photos-deduper-worker-1            Created                                                                                                                     0.1s 
 ✔ Container google-photos-deduper-nginx-1             Created                                                                                                                     0.1s 
Attaching to client-1, flower-1, mongo-1, nginx-1, redis-1, server-1, worker-1
redis-1   | 10:C 20 Jan 2024 01:49:57.885 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis-1   | 10:C 20 Jan 2024 01:49:57.887 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-1   | 10:C 20 Jan 2024 01:49:57.887 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=10, just started
redis-1   | 10:C 20 Jan 2024 01:49:57.887 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis-1   | 10:M 20 Jan 2024 01:49:57.887 * monotonic clock: POSIX clock_gettime
redis-1   | 10:M 20 Jan 2024 01:49:57.888 * Running mode=standalone, port=6379.
redis-1   | 10:M 20 Jan 2024 01:49:57.888 * Server initialized
redis-1   | 10:M 20 Jan 2024 01:49:57.888 * Ready to accept connections tcp
mongo-1   | {"t":{"$date":"2024-01-20T01:49:57.933+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
mongo-1   | {"t":{"$date":"2024-01-20T01:49:57.937+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
mongo-1   | {"t":{"$date":"2024-01-20T01:49:57.937+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"fdc8b05dec19"}}
mongo-1   | {"t":{"$date":"2024-01-20T01:49:57.937+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.28","gitVersion":"61c2baf63a060f7c12bd76e779044800ae18710b","openSSLVersion":"OpenSSL 1.1.1f  31 Mar 2020","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2004","distarch":"aarch64","target_arch":"aarch64"}}}}
mongo-1   | {"t":{"$date":"2024-01-20T01:49:57.937+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"20.04"}}}
mongo-1   | {"t":{"$date":"2024-01-20T01:49:57.937+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"}}}}
mongo-1   | {"t":{"$date":"2024-01-20T01:49:57.938+00:00"},"s":"I",  "c":"STORAGE",  "id":22297,   "ctx":"initandlisten","msg":"Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem","tags":["startupWarnings"]}
mongo-1   | {"t":{"$date":"2024-01-20T01:49:57.938+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=3411M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
Gracefully stopping... (press Ctrl+C again to force)
[+] Killing 0/0
[+] Stopping 4/5gle-photos-deduper-worker-1  Killing                                                                                                                               0.1s 
 ⠹ Container google-photos-deduper-worker-1  Killing                                                                                                                               0.3s 
 ✔ Container google-photos-deduper-flower-1  Killed                                                                                                                                0.3s 
 ✔ Container google-photos-deduper-redis-1   Killed                                                                                                                                0.2s 
 ⠹ Container google-photos-deduper-worker-1  Stopping                                                                                                                              0.3s 
[+] Stopping 7/5gle-photos-deduper-mongo-1   Killed                                                                                                                                0.2s 
 ✔ Container google-photos-deduper-worker-1  Stopped                                                                                                                               0.3s 
 ✔ Container google-photos-deduper-nginx-1   Stopped                                                                                                                               0.0s 
 ✔ Container google-photos-deduper-flower-1  Stopped                                                                                                                               0.3s 
 ✔ Container google-photos-deduper-client-1  Stopped                                                                                                                               0.3s 
 ✔ Container google-photos-deduper-server-1  Stopped                                                                                                                               0.0s 
 ✔ Container google-photos-deduper-redis-1   Stopped                                                                                                                               0.0s 
 ✔ Container google-photos-deduper-mongo-1   Stopped                                                                                                                               0.0s 
redis-1 exited with code 137
mongo-1 exited with code 137
flower-1 exited with code 0
flower-1 exited with code 137
client-1 exited with code 0
client-1 exited with code 137
worker-1 exited with code 0
worker-1 exited with code 137
Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:5000 -> 0.0.0.0:0: listen tcp 0.0.0.0:5000: bind: address already in use

**Comment by guerda** [comment]
Is it possible that another process is already using the port 5000?

The error says 

    listen tcp 0.0.0.0:5000: bind: address already in use

This could be another docker container or another Flask process.

**Comment by brianhughesspe** [comment]
I had the same port 5000 issue. Apparently Apple changes something with the AirPlay Receiver and it now uses that port. If you go to system settings and search for receiver, choose AirPlay Receiver, and then turn it off. Once you do that you can restart the docker-compose up and it'll install.

**Comment by mtalcott** [comment]
Fixed by https://github.com/mtalcott/google-photos-deduper/pull/48
