### ISSUE TITLE
Deleting Photo Fails

### ISSUE THREAD

**Issue by cryptoDevTrader** [mtalcott/google-photos-deduper#40]
After selecting duplicates and clicking the Delete Duplicates button, a new window is launched with each photo in question, but fails to delete. Inspecting the service worker yields the following error:

`service_worker.ts-72f4954d.js:1 navigateAndDelete error Timeout: failed to delete mediaItem <id> within 10s, skipping`

It doesn't appear as though the extension is clicking the delete button for some reason. Has Google changed things a bit to make the extension no longer function?

**Comment by sanjuruk** [comment]
Same issue here.

**Comment by mtalcott** [comment]
This should be fixed by https://github.com/mtalcott/google-photos-deduper/pull/49. Please pull the latest from `main` branch and try again!
