### ISSUE TITLE
Any plans to automate installation and set up?

### ISSUE THREAD

**Issue by millsmcewan** [mtalcott/google-photos-deduper#43]
Hello

Your app looks extremely helpful.  I note that it includes some steps that look rather daunting such as:
4. Set up local environment variables.
cp example.env .env
Generate [FLASK_SECRET_KEY](https://flask.palletsprojects.com/en/2.3.x/config/#SECRET_KEY) with python -c 'import secrets; print(secrets.token_hex())' and add it to .env.
Add GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET from the client_id and client_secret values from the client secret file created above.

Do you have any plans to package it in such a way that installation and operation is easier for people who are less technical?  Thank you

**Comment by mtalcott** [comment]
Yes, eventually I would like to [create a publicly accessible, hosted version of the app](https://github.com/mtalcott/google-photos-deduper/wiki#hosted-app) which would remove _all_ of the need for technical setup. You'd simply go to a website. Unfortunately, I'm not able to invest the time required to do that anytime soon.
