### ISSUE TITLE
Don;'t delete duplicates

### ISSUE THREAD

**Issue by elgodox** [mtalcott/google-photos-deduper#47]
When I want to delete duplicate photos it opens a new tab and gets stuck there, does not continue, and does not delete duplicates. why?
![image](https://github.com/mtalcott/google-photos-deduper/assets/57495341/9886ff93-5fd4-417d-8bbb-a08affdd8e82)

**Comment by matthewknill** [comment]
Yeah for me it loads the images but it doesn't press the button and just fails

**Comment by brianhughesspe** [comment]
This is a dupe of [https://github.com/mtalcott/google-photos-deduper/issues/40](https://github.com/mtalcott/google-photos-deduper/issues/40) which it doesn't seem like has been fixed yet.

**Comment by mtalcott** [comment]
Closing as dupe of #40
