### ISSUE TITLE
Service worker registration failed.

### ISSUE THREAD

**Issue by elgodox** [mtalcott/google-photos-deduper#51]
After building the chrome extension and importing, it gives this error

![image](https://github.com/mtalcott/google-photos-deduper/assets/57495341/cb68d35d-75b0-4399-8c22-ab0e80f17563)

**Comment by anthonyjclarke** [comment]
I have this issue, I wonder how you fixed this?

**Comment by mtalcott** [comment]
Make sure you're loading the Chrome extension from the chrome_extension/**dist**/ directory, not just `chrome_extension/`. I get this error if I try to load it from the latter.

I pushed an update to make loading from the `chrome_extension/` directory fail earlier in the process: https://github.com/mtalcott/google-photos-deduper/pull/52

**Comment by anthonyjclarke** [comment]
That fixed it! Thanks
