### ISSUE TITLE
Suggest improvements to README

### ISSUE THREAD

**Issue by alexkuang0** [mtalcott/google-photos-deduper#6]
Hi Mack! Thanks for the project!

However, there are some unmentioned points (or easily missed when reading the official docs) to get the app up and running. So I would suggest mention the following:

1. enable **Photos Library API** in Google Cloud console.
2. in OAuth client configuration, add `http://localhost/auth/google/callback` to "Authorized redirect URIs"
3. in OAuth consent screen settings, add your Gmail to test users.

**Comment by Randl** [comment]
Also worth mentioning is the required version of npm for the Chrome extension. Apparently I had too old one installed

**Comment by mtalcott** [comment]
I forgot about enabling the Photos API and creating the Google Cloud project. I'll go through that and add the steps, thanks!

@Randl will also add a target node version on the package.json - thanks

**Comment by mtalcott** [comment]
Addressed with https://github.com/mtalcott/google-photos-deduper/pull/10 and https://github.com/mtalcott/google-photos-deduper/pull/11
