### ISSUE TITLE
Chrome extension: Refused to load the script

### ISSUE THREAD

**Issue by Neirop** [mtalcott/google-photos-deduper#66]
![Screenshot from 2024-10-19 12-18-29](https://github.com/user-attachments/assets/efacf5d5-3bff-43e1-b90b-e4bb4ac30f27)

**Comment by mtalcott** [comment]
Thanks for the heads up @Neirop. Looks like this is caused by https://github.com/crxjs/chrome-extension-tools/issues/918. I will see if I can find a workaround.

**Comment by mtalcott** [comment]
Resolved by https://github.com/mtalcott/google-photos-deduper/pull/67.

@Neirop I'd appreciate if you could pull the latest from `main` and confirm the issue is resolved.

**Comment by Neirop** [comment]
I still get the same error
