### ISSUE TITLE
Stock on Chrome Extension

### ISSUE THREAD

**Issue by neydor21** [mtalcott/google-photos-deduper#68]
I was able to run the project, but the last part I'm getting an error with the chrome extension. Any Suggestions? 

![Screenshot 2024-10-29 095752](https://github.com/user-attachments/assets/6c69f1d5-cfe0-4bcd-89ce-4c36eeba9831)
![Screenshot 2024-10-29 095902](https://github.com/user-attachments/assets/daccc219-cd5f-4301-ab2b-8fa0ced51950)

**Comment by mtalcott** [comment]
Hi @neydor21, this should have been fixed with https://github.com/mtalcott/google-photos-deduper/pull/67.

Can you try:
1. Pull the latest from `main` branch
2. In `chrome_extension/` directory, reinstall npm packages
  2a. Run `npm install` , or
  2b. Run `docker compose build`

And let me know if that fixes your issue?

**Comment by neydor21** [comment]
Sorry but I'm still having the same issue.

**Comment by cristianorbs** [comment]
I'm also having this issue and I found this Reddit about it: https://www.reddit.com/r/webdev/comments/1gf0v2p/comment/lukv1vm/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

They're suggesting to update vite-plugin to version 2.0.0-beta.26. I'll give it a try when I get to my personal computer and will post an update.

**Comment by mtalcott** [comment]
@neydor21 @cristianorbs Alright, I [merged the upgraded package](https://github.com/mtalcott/google-photos-deduper/pull/69), give it a shot now!

**Comment by cristianorbs** [comment]
It worked, @mtalcott! Thank you very much.
@neydor21 just don't forget the run npm install after pulling the latest changes.
In case anyone else needs:
1. Pull the changes
2. npm install inside chrome_extension
3. npm run build
4. Reload the code from the extension inside Chrome

**Comment by neydor21** [comment]
If I compose up the docker-compose inside the chrome_extension after fetching the latest changes from github and then reload the extension inside chrome this should work right? If this is correct I'm still seen the issue. What I might be doing wrong? I'm working on Windows 11.

**Comment by cristianorbs** [comment]
@neydor21 how are you running the docker-compose?
You can do the following:
`docker compose -f chrome_extension/docker-compose.yml run node npm install`
And then:
`docker compose -f chrome_extension/docker-compose.yml run node npm run build`
Maybe you're missing the install part, which will actually update the plugin to the latest version

**Comment by neydor21** [comment]
Got it fix. My Execution Policy were set to Restricted.

**Comment by neydor21** [comment]
I am experiencing this issue again.
