### ISSUE TITLE
Failing at Process Duplicates

### ISSUE THREAD

**Issue by anthonyjclarke** [mtalcott/google-photos-deduper#70]
Trying again after a pause of a few months... making progress (I think!)

<img width="826" alt="Google Chrome 2024-11-03 11 18 47" src="https://github.com/user-attachments/assets/009d9d91-597a-4636-b87d-b83275b865a5">

This completes and then I get a

<img width="799" alt="Google Chrome 2024-11-03 11 49 45" src="https://github.com/user-attachments/assets/cdb8adf1-1892-4018-b9fb-5b8f47f60797">

Checking the Celery Log, last entry

> 100%|██████████| 150895/150895 [31:36<00:00, 79.56it/s] 
> [2024-11-03 00:49:18,948: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 0.')
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
>     raise WorkerLostError(
> billiard.einfo.ExceptionWithTraceback: 
> """
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
>     raise WorkerLostError(
> billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 0.
> """

Any advice to help diagnose the issue?

Many thanks

**Comment by anthonyjclarke** [comment]
Did a complete download / rebuild, ran again..... failed....

<img width="781" alt="image" src="https://github.com/user-attachments/assets/8e6e0468-1d10-4616-a420-b45a85efec2c">

```
100%|██████████| 150897/150897 [20:31<00:00, 122.56it/s]
[2024-11-03 06:40:12,140: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 0.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.einfo.ExceptionWithTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 0.
"""
```

**Comment by mtalcott** [comment]
@anthonyjclarke It's likely that the container is being terminated because it ran out of memory. Can you try [increasing your memory limit in Docker Desktop settings](https://docs.docker.com/desktop/settings-and-maintenance/settings/#advanced)?

**Comment by anthonyjclarke** [comment]
<img width="626" alt="Greenshot 2024-11-10 07 55 08" src="https://github.com/user-attachments/assets/99f1396a-60f6-4f15-a9cf-af03e13cd851">

@mtalcott Thanks, that worked.... increased to 12Gb Memory and 2GB Swap
