### ISSUE TITLE
"Move to Trash"

### ISSUE THREAD

**Issue by Monica6128** [mtalcott/google-photos-deduper#71]
Do I have to click "move to trash" on every photo delete? I am getting the message that they are failing to delete whether I click it manually or not. Did I miss something?

**Comment by eddiehorng** [comment]
I have the same experience, but click on "move to trash" manually should work.
document.querySelector('[jsshadow] [autofocus]') doesn't find "move to trash" button, maybe photos frontend is changed recently?

**Comment by neydor21** [comment]
Im facing the same issues as well.

**Comment by daksh96sharma** [comment]
Yes I dealt with this issue as well; it's not great. So I used the following script on my Mac when it's idle (overnight)

repeat
	tell application "System Events"
		keystroke return
	end tell
	delay 5
end repeat

**Comment by Monica6128** [comment]
Oh - I am on PC. Hopefully it can be figured out.

**Comment by mtalcott** [comment]
Hi all - this should be fixed by https://github.com/mtalcott/google-photos-deduper/pull/73. Please pull the latest and confirm it resolves the issue for you.

**Comment by neydor21** [comment]
Working For me now! Thanks
