### ISSUE TITLE
Chrome Extension Error

### ISSUE THREAD

**Issue by anthonyjclarke** [mtalcott/google-photos-deduper#74]
Nearly there @mtalcott ! Thanks for help

Re-installed fully, newest version, rebuilt extension

Appears Greyed out and on checking see this error

<img width="669" alt="image" src="https://github.com/user-attachments/assets/578ef00c-f0ca-45af-9423-c16be1fa75f1">

Refused to load the script 'chrome-extension://159e144f-9deb-4415-9f04-83593fd76e31/assets/app_content.ts-01330430.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by anthonyjclarke** [comment]
![image](https://github.com/user-attachments/assets/7a122d34-e5a8-4269-a5f1-086ca0096bbb)

<img width="345" alt="image" src="https://github.com/user-attachments/assets/a86db4a9-3bad-422d-8990-a6c8e86ce590">

**Comment by anthonyjclarke** [comment]
Did some research through closed issues... found this post https://github.com/mtalcott/google-photos-deduper/issues/68 

and decided (randomly!) to follow these intructions, thanks @cristianorbs

<img width="629" alt="Google Chrome 2024-11-11 06 04 15" src="https://github.com/user-attachments/assets/35c9a0c8-2237-498d-82fd-7e895db4d041">

I did not have NVM installed, so Installed using Brew...followed the details above, then reloaded extension etc etc

And...

<img width="1038" alt="image" src="https://github.com/user-attachments/assets/d4039c52-27ae-4430-a6d2-a8812118a635">


Not sure if this will help others but wanted to share

**Comment by neydor21** [comment]
I'm facing this again. Did something change within Chrome?
