### ISSUE TITLE
Having issue with starting up Docker image

### ISSUE THREAD

**Issue by shivamkadbhane** [mtalcott/google-photos-deduper#80]
I am getting the below error after running docker compose. I have already tried upgrading and downgrading python version as well as mediapipe version.

Current mediapipe version - 0.10.20
Current python version - Python 3.12.8

```
8.370 ERROR: Ignored the following versions that require a different python version: 1.3.1 Requires-Python >=3.10; 3.10.0 Requires-Python >=3.10; 3.10.0rc1 Requires-Python >=3.10
8.370 ERROR: Could not find a version that satisfies the requirement mediapipe==0.10.3 (from versions: 0.10.5, 0.10.7, 0.10.8, 0.10.9, 0.10.10, 0.10.11, 0.10.13, 0.10.14, 0.10.15, 0.10.18, 0.10.20)
8.370 ERROR: No matching distribution found for mediapipe==0.10.3
8.460
[+] Running 0/2A new release of pip is available: 23.0.1 -> 24.3.1
 - Service server  Building                                                                                       10.7s
 - Service worker  Building                                                                                       10.7s
failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
```

**Comment by mtalcott** [comment]
Hi @shivamkadbhane, the project currently supports Python 3.9 and mediapipe 0.10.3. Are you following the provided setup instructions?

**Comment by shivamkadbhane** [comment]
Hi I had an higher version of python instalelled. I installed 3.9 but I was still facing same issue. The 0.10.3 version was not being downloaded so I bumped up the version in the requirements.txt to 0.10.5 and I was able to get it to work. Seems to be working now. Thanks a lot.
